# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk15

services:
  - postgresql

before_install:
  - psql -c 'create database rest;' -U postgres

install: true

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - romankhiropulos@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="dfd5af10-fcec-4884-9bb5-1bbd76c2794a"